# Numpy

## Import Librarires

In [1]:
!pip install numpy

In [2]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

## 1D Array

In [3]:
a = np.array([1,2,3,4,5,6,7])

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7])

### Zero array

In [15]:
b1 = np.zeros(4)
b1

array([0., 0., 0., 0.])

### Array of 1s

In [7]:
b = np.ones(4)
b

array([1., 1., 1., 1.])

### Empty Array

In [8]:
c = np.empty(4)
c

array([1., 1., 1., 1.])

### Arange

In [10]:
d = np.arange(14)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [12]:
e = np.arange(2,14)
e

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [14]:
f = np.arange(2,34,3) #with differences
f

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

### Linearly Space Arrays

In [17]:
g = np.linspace(0,100 , 6)  #6 is number of elements linearly separated
g

array([  0.,  20.,  40.,  60.,  80., 100.])

### Specific Data type in arrays

In [18]:
h = np.ones(9, dtype=np.int8)
h

array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [19]:
i = np.ones(9, dtype=np.float16)
i

array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float16)

In [21]:
j = np.ones(9, dtype=np.str_)
j

array(['1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

## 2D Arrays

In [23]:
b1 = np.zeros((4,6))
b1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.empty((3,2))

array([[  0.,  20.],
       [ 40.,  60.],
       [ 80., 100.]])

## 3D Array

### Making and Reshaping 3D array

In [31]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
d = np.arange(90).reshape(3,5,6)
d

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])

## Practicing Numpy

In [4]:
food = np.array(['biscuit', 'chips', 'nuts'])
food

array(['biscuit', 'chips', 'nuts'], dtype='<U7')

In [5]:
prices = np.array([10,20,30])
prices


array([10, 20, 30])

In [6]:
type(prices)

numpy.ndarray

In [7]:
type(food)

numpy.ndarray

In [8]:
len(food)

3

In [9]:
len(prices)

3

In [11]:
prices[2]

30

In [13]:
food[:2]

array(['biscuit', 'chips'], dtype='<U7')

In [14]:
prices.mean()

20.0

In [15]:
prices.std()

8.16496580927726

In [16]:
emp=np.empty(6)
emp

array([0.e+000, 5.e-323, 0.e+000, 0.e+000, 0.e+000, 0.e+000])

In [17]:
np.arange(3,100,9)

array([ 3, 12, 21, 30, 39, 48, 57, 66, 75, 84, 93])

### Array functions

In [21]:
a = np.array([5,6,2,1,6,78,78886,432,232,12,3])
a

array([    5,     6,     2,     1,     6,    78, 78886,   432,   232,
          12,     3])

In [22]:
a.sort()
a

array([    1,     2,     3,     5,     6,     6,    12,    78,   232,
         432, 78886])

In [28]:
a.all()

True

In [30]:
a.any()

True

In [25]:
a.argmax()

10

In [35]:
b = np.array([5,2,1,3.0,77.0,.12,-22])
b

array([  5.  ,   2.  ,   1.  ,   3.  ,  77.  ,   0.12, -22.  ])

In [36]:
c=np.concatenate((a,b))

In [37]:
c

array([ 1.0000e+00,  2.0000e+00,  3.0000e+00,  5.0000e+00,  6.0000e+00,
        6.0000e+00,  1.2000e+01,  7.8000e+01,  2.3200e+02,  4.3200e+02,
        7.8886e+04,  5.0000e+00,  2.0000e+00,  1.0000e+00,  3.0000e+00,
        7.7000e+01,  1.2000e-01, -2.2000e+01])

In [38]:
c.sort()

In [39]:
c

array([-2.2000e+01,  1.2000e-01,  1.0000e+00,  1.0000e+00,  2.0000e+00,
        2.0000e+00,  3.0000e+00,  3.0000e+00,  5.0000e+00,  5.0000e+00,
        6.0000e+00,  6.0000e+00,  1.2000e+01,  7.7000e+01,  7.8000e+01,
        2.3200e+02,  4.3200e+02,  7.8886e+04])

In [40]:
#2d Arrays

In [49]:
a = np.array([[4,5,6],[44,55,66]])
a

array([[ 4,  5,  6],
       [44, 55, 66]])

In [50]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
c = np.concatenate((a,b))

In [52]:
c

array([[ 4,  5,  6],
       [44, 55, 66],
       [ 1,  2,  3],
       [ 4,  5,  6]])

### Concatenation around the axis

In [53]:
d= np.concatenate((a,b), axis = 0)
d

array([[ 4,  5,  6],
       [44, 55, 66],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [54]:
e = np.concatenate((a,b),axis =1)
e

array([[ 4,  5,  6,  1,  2,  3],
       [44, 55, 66,  4,  5,  6]])

In [55]:
len(e)

2

In [56]:
len(d)

4

### Ndim, Shape and Reshape

In [68]:
f = np.array([[[4,5,6,7,8],[44,55,66,1,2]], [[2,4,6,2,1],[3,5,67,3,2]], [[7,7,7,1,2],[9,8,7,0,2]]])
f

array([[[ 4,  5,  6,  7,  8],
        [44, 55, 66,  1,  2]],

       [[ 2,  4,  6,  2,  1],
        [ 3,  5, 67,  3,  2]],

       [[ 7,  7,  7,  1,  2],
        [ 9,  8,  7,  0,  2]]])

In [69]:
f.ndim

3

In [70]:
g = np.array([[1,2,3],[4,5,6],[9,8,7]])
g

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [71]:
g.ndim

2

In [72]:
f.size

30

In [73]:
f.shape

(3, 2, 5)

In [80]:
a = np.arange(12)

In [81]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
np.reshape(a, newshape=(4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Converting 1D to 2D

In [85]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [86]:
a.shape

(12,)

In [89]:
b = a[np.newaxis, :] # add new axis (row wise conversion)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [88]:
b.shape

(1, 12)

In [90]:
c = a[:,np.newaxis] # add new axis (Column wise conversion)

In [91]:
c

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [92]:
a[2:7]

array([2, 3, 4, 5, 6])

In [93]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
a*6 # multiiplying array with scalor number

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66])

In [95]:
a+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [96]:
a.sum()

66

In [97]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
a.mean()

5.5