In [2]:
# Importing Libraries
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


## Importing data set

In [3]:
df = pd.read_csv('ml_data_salary.csv')
print(df.head(30))

     age  distance  YearsExperience  Salary
0   31.1     77.75              1.1   39343
1   31.3     78.25              1.3   46205
2   31.5     78.75              1.5   37731
3   32.0     80.00              2.0   43525
4   32.2     80.50              2.2   39891
5   32.9     82.25              2.9   56642
6   33.0     82.50              3.0   60150
7   33.2     83.00              3.2   54445
8   33.2     83.00              3.2   64445
9   33.7     84.25              3.7   57189
10  33.9     84.75              3.9   63218
11  34.0     85.00              4.0   55794
12  34.0     85.00              4.0   56957
13  34.1     85.25              4.1   57081
14  34.5     86.25              4.5   61111
15  34.9     87.25              4.9   67938
16  35.1     87.75              5.1   66029
17  35.3     88.25              5.3   83088
18  35.9     89.75              5.9   81363
19  36.0     90.00              6.0   93940
20  36.8     92.00              6.8   91738
21  37.1     92.75              

In [4]:
descriptive_features = df[['age','distance','YearsExperience']]
target_feature = df[['Salary']]
descriptive_features.head(), target_feature.head()

(    age  distance  YearsExperience
 0  31.1     77.75              1.1
 1  31.3     78.25              1.3
 2  31.5     78.75              1.5
 3  32.0     80.00              2.0
 4  32.2     80.50              2.2,
    Salary
 0   39343
 1   46205
 2   37731
 3   43525
 4   39891)

## Importing Linear regression and efficiency measures from sklearn 

In [16]:
# Importing Linear regression from sklearn 
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error

## Fitting Multiple Linear Regression to the data set

In [6]:
# Fitting Multiple Linear Regression to the data set
from sklearn.linear_model import Ridge
regressor = Ridge()
regressor.fit(descriptive_features, target_feature)

Ridge()

## Predicting  results

In [9]:
# Predicting the Test set results
y_pred = regressor.predict(descriptive_features)
y_pred

array([[ 36207.81198614],
       [ 38096.82407541],
       [ 39985.83616467],
       [ 44708.36638784],
       [ 46597.3784771 ],
       [ 53208.92078953],
       [ 54153.42683416],
       [ 56042.43892343],
       [ 56042.43892343],
       [ 60764.96914659],
       [ 62653.98123586],
       [ 63598.48728049],
       [ 63598.48728049],
       [ 64542.99332512],
       [ 68321.01750365],
       [ 72099.04168219],
       [ 73988.05377145],
       [ 75877.06586072],
       [ 81544.10212851],
       [ 82488.60817314],
       [ 90044.65653021],
       [ 92878.1746641 ],
       [100434.22302116],
       [103267.74115506],
       [107990.27137823],
       [110823.78951212],
       [115546.31973529],
       [116490.82577992],
       [123102.36809235],
       [124991.38018161]])

## Score of model

In [10]:
regressor.score(descriptive_features,target_feature)

0.9569564066557392

## Evaluation by Mean Squared Error

In [14]:
## Evaluation by Mean Squared Error
#computing the squared error of the first model
print("Mean squared error model 1: %.2f" % mean_squared_error(target_feature, y_pred))
print("Mean Absolute error model 1: %.2f" % mean_absolute_error(target_feature, y_pred))

Mean squared error model 1: 31271138.79
Mean Absolute error model 1: 4644.37


## Coefficient and Intercept

In [12]:

#print coefficient and intercept
print('Coefficients: \n', regressor.coef_)
print('Intercept: \n', regressor.intercept_)

Coefficients: 
 [[1144.85581168 2862.13952919 1144.85581168]]
Intercept: 
 [-223187.89354436]


In [15]:
# Predicting the Test set results
y_pred2 = regressor.predict([[31.1,77.70,1.3]])
y_pred2

array([[36293.67617202]])